theme: jekyll-theme-slate
site_name: LogoJS
repo_name: logojs-package
repo_url: https://www.github.com/weng-lab/logojs-package
site_description: "LogoJS Javascript sequence logos"
site_author: Henry Pratt
remote_branch: master

copyright: "Copyright &copy; 2019 Weng Lab"

navbar-links:
  Basic logos:
    - DNA and RNA: "dnalogo"
    - Protein: "proteinlogo"

plugins:
  - jekyll-paginate
  - jekyll-sitemap
